import type { QueueItem } from "./types";

/**
 * Fake queue so the app runs with zero credentials.
 *
 * Safe for a public repo / portfolio screenshots: every customer, ticket, and
 * bot review is invented. No real company, no real emails, no Slashy staff.
 */
export const mockQueue: QueueItem[] = [
  {
    id: "acme-labs/api#482",
    repo: "acme-labs/api",
    number: 482,
    title: "Login fails after password reset on mobile",
    author: "maya",
    url: "https://github.com/acme-labs/api/pull/482",
    createdAt: "2026-08-16T09:12:00Z",
    updatedAt: "2026-08-17T08:40:00Z",
    ticket: {
      id: "ENG-311",
      title: "Login fails after password reset on mobile",
      description:
        "Customer Jane Doe (Northwind Retail) reports that after resetting their password from the iOS app, they land on a blank screen and can't sign in. Reproduced on iOS 18.2, app 4.3.1. Desktop web works fine. They need this fixed before Monday's board demo.",
      url: "https://linear.app/acme-labs/issue/ENG-311",
      customerField: "Northwind Retail",
      customer: {
        name: "Northwind Retail",
        domains: ["northwind.example"],
        emails: ["jane@northwind.example"],
        tier: null,
      },
      filedBy: { name: "Maya Chen", email: "maya@acme-labs.example" },
    },
    customer: {
      name: "Northwind Retail",
      email: "jane@northwind.example",
      source: "linear",
      verified: true,
      candidates: [],
      trail: ["email found in ticket text"],
    },
    problem: "After reset on iOS they hit a blank screen and can't sign in.",
    gate: {
      ciGreen: true,
      ciState: "passing",
      unresolvedBotReviews: 0,
      blockingBots: [],
    },
    mergeable: true,
    blockedReason: null,
  },
  {
    id: "acme-labs/web#91",
    repo: "acme-labs/web",
    number: 91,
    title: "Billing webhook retry loop",
    author: "jordan",
    url: "https://github.com/acme-labs/web/pull/91",
    createdAt: "2026-08-16T14:03:00Z",
    updatedAt: "2026-08-16T18:20:00Z",
    ticket: {
      id: "ENG-402",
      title: "Duplicate invoices from webhook retries",
      description:
        "Globex saw duplicate invoices when our billing webhook retried on timeout. Need idempotency keys on the handler.\n\n**Claude review (unresolved):**\n> This handler can still double-charge if two retries land in the same second. Add an idempotency key on `invoice_id` before inserting.",
      url: "https://linear.app/acme-labs/issue/ENG-402",
      customerField: null,
      customer: null,
      filedBy: { name: "Jordan Lee", email: "jordan@acme-labs.example" },
    },
    customer: {
      name: "Sam Ortiz",
      email: "sam@globex.example",
      source: "supabase",
      verified: true,
      candidates: [],
      trail: ['name in ticket: "Sam Ortiz"', "supabase: 1 match"],
    },
    problem: "Duplicate invoices from webhook retries - needs idempotency.",
    gate: {
      ciGreen: true,
      ciState: "passing",
      unresolvedBotReviews: 2,
      blockingBots: ["claude[bot]"],
    },
    mergeable: false,
    blockedReason: "2 unresolved bot reviews (claude[bot])",
  },
  {
    id: "acme-labs/api#488",
    repo: "acme-labs/api",
    number: 488,
    title: "Add rate limit to export endpoint",
    author: "maya",
    url: "https://github.com/acme-labs/api/pull/488",
    createdAt: "2026-08-17T02:40:00Z",
    updatedAt: "2026-08-17T05:10:00Z",
    ticket: {
      id: "ENG-410",
      title: "Export endpoint abused by a script",
      description:
        "A user hammered the export endpoint overnight. Add a per-user rate limit. Reporter only left a first name in the thread: 'Priya'.",
      url: "https://linear.app/acme-labs/issue/ENG-410",
      customerField: null,
      customer: null,
      filedBy: { name: "Maya Chen", email: "maya@acme-labs.example" },
    },
    customer: {
      name: "Priya",
      email: null,
      source: "posthog",
      verified: false,
      candidates: [
        { email: "priya@contoso.example", source: "posthog", note: "Priya Nair" },
        {
          email: "priya.n@contoso.example",
          source: "supabase",
          note: "Priya N.",
        },
      ],
      trail: ['name in ticket: "Priya"', "2 candidates - needs a pick"],
    },
    problem: "Export endpoint abused - add per-user rate limit.",
    gate: {
      ciGreen: false,
      ciState: "failing",
      unresolvedBotReviews: 0,
      blockingBots: [],
    },
    mergeable: false,
    blockedReason: "CI not green",
  },
  {
    id: "acme-labs/web#104",
    repo: "acme-labs/web",
    number: 104,
    title: "Dark mode dashboard charts render white",
    author: "priya",
    url: "https://github.com/acme-labs/web/pull/104",
    createdAt: "2026-08-17T10:20:00Z",
    updatedAt: "2026-08-17T12:05:00Z",
    ticket: {
      id: "ENG-418",
      title: "Charts unreadable in dark mode",
      description:
        "Initech switched to dark mode and every chart axis renders white-on-white. Only the analytics dashboard is affected.",
      url: "https://linear.app/acme-labs/issue/ENG-418",
      customerField: "Initech",
      customer: {
        name: "Initech",
        domains: ["initech.example"],
        emails: ["dana@initech.example"],
        tier: null,
      },
      filedBy: { name: "Priya Nair", email: "priya@acme-labs.example" },
    },
    customer: {
      name: "Initech",
      email: "dana@initech.example",
      source: "linear",
      verified: true,
      candidates: [],
      trail: ["linear customer record"],
    },
    problem: "Dark mode charts render white-on-white on the analytics dashboard.",
    gate: {
      ciGreen: true,
      ciState: "passing",
      unresolvedBotReviews: 0,
      blockingBots: [],
    },
    mergeable: true,
    blockedReason: null,
  },
  {
    id: "acme-labs/api#495",
    repo: "acme-labs/api",
    number: 495,
    title: "Cache stale plan after upgrade",
    author: "jordan",
    url: "https://github.com/acme-labs/api/pull/495",
    createdAt: "2026-08-17T13:15:00Z",
    updatedAt: "2026-08-17T15:42:00Z",
    ticket: {
      id: "ENG-421",
      title: "Upgraded customers still see the free plan",
      description:
        "Umbrella Co upgraded to Pro but the app kept showing free-tier limits for ~10 minutes. Plan cache isn't invalidated on upgrade.",
      url: "https://linear.app/acme-labs/issue/ENG-421",
      customerField: "Umbrella Co",
      customer: {
        name: "Umbrella Co",
        domains: ["umbrella.example"],
        emails: ["leon@umbrella.example"],
        tier: null,
      },
      filedBy: { name: "Jordan Lee", email: "jordan@acme-labs.example" },
    },
    customer: {
      name: "Umbrella Co",
      email: "leon@umbrella.example",
      source: "supabase",
      verified: true,
      candidates: [],
      trail: ["supabase: 1 match on domain"],
    },
    problem: "Plan cache not invalidated on upgrade - Pro users see free limits.",
    gate: {
      ciGreen: true,
      ciState: "pending",
      unresolvedBotReviews: 0,
      blockingBots: [],
    },
    mergeable: false,
    blockedReason: "Checks are still running",
  },
  {
    id: "acme-labs/api#498",
    repo: "acme-labs/api",
    number: 498,
    title: "Escape user input in CSV export",
    author: "maya",
    url: "https://github.com/acme-labs/api/pull/498",
    createdAt: "2026-08-17T16:02:00Z",
    updatedAt: "2026-08-17T17:30:00Z",
    ticket: {
      id: "ENG-425",
      title: "Formula injection risk in CSV export",
      description:
        "Security review flagged that exported CSVs don't escape leading =, +, - or @, so a crafted field can execute in spreadsheet apps.\n\n**Claude review (unresolved):**\n> Prefix risky cells with a single quote, but also strip control characters - a tab before `=` still triggers evaluation in some clients.",
      url: "https://linear.app/acme-labs/issue/ENG-425",
      customerField: null,
      customer: null,
      filedBy: { name: "Maya Chen", email: "maya@acme-labs.example" },
    },
    customer: {
      name: null,
      email: null,
      source: "none",
      verified: false,
      candidates: [],
      trail: ["internal security finding - no external customer"],
    },
    problem: "CSV export doesn't escape formula characters - injection risk.",
    gate: {
      ciGreen: true,
      ciState: "passing",
      unresolvedBotReviews: 1,
      blockingBots: ["claude[bot]"],
    },
    mergeable: false,
    blockedReason: "1 unresolved bot review (claude[bot])",
  },
  {
    id: "acme-labs/web#110",
    repo: "acme-labs/web",
    number: 110,
    title: "Onboarding email links point to staging",
    author: "priya",
    url: "https://github.com/acme-labs/web/pull/110",
    createdAt: "2026-08-18T08:45:00Z",
    updatedAt: "2026-08-18T09:20:00Z",
    ticket: {
      id: "ENG-430",
      title: "Welcome email links go to staging",
      description:
        "Wonka Inc reported that links in the welcome email open the staging site. Base URL isn't set from env in the email templates.",
      url: "https://linear.app/acme-labs/issue/ENG-430",
      customerField: null,
      customer: null,
      filedBy: { name: "Priya Nair", email: "priya@acme-labs.example" },
    },
    customer: {
      name: "Charlie Bucket",
      email: "charlie@wonka.example",
      source: "posthog",
      verified: true,
      candidates: [],
      trail: ['name in ticket: "Charlie"', "posthog: 1 match"],
    },
    problem: "Welcome email links point at staging instead of production.",
    gate: {
      ciGreen: true,
      ciState: "passing",
      unresolvedBotReviews: 0,
      blockingBots: [],
    },
    mergeable: true,
    blockedReason: null,
  },
  {
    id: "acme-labs/api#501",
    repo: "acme-labs/api",
    number: 501,
    title: "Fix timezone drift in scheduled reports",
    author: "leo",
    url: "https://github.com/acme-labs/api/pull/501",
    createdAt: "2026-08-18T07:10:00Z",
    updatedAt: "2026-08-18T11:48:00Z",
    ticket: {
      id: "ENG-433",
      title: "Weekly reports arrive an hour late after DST",
      description:
        "Stark Industries reports weekly digests arriving an hour off since the DST change. Scheduler stores local time instead of UTC.",
      url: "https://linear.app/acme-labs/issue/ENG-433",
      customerField: "Stark Industries",
      customer: {
        name: "Stark Industries",
        domains: ["stark.example"],
        emails: ["pepper@stark.example"],
        tier: null,
      },
      filedBy: { name: "Leo Park", email: "leo@acme-labs.example" },
    },
    customer: {
      name: "Stark Industries",
      email: "pepper@stark.example",
      source: "linear",
      verified: true,
      candidates: [],
      trail: ["linear customer record"],
    },
    problem: "Scheduled reports drift an hour after DST - scheduler stores local time.",
    gate: {
      ciGreen: true,
      ciState: "passing",
      unresolvedBotReviews: 0,
      blockingBots: [],
    },
    mergeable: true,
    blockedReason: null,
  },
  {
    id: "acme-labs/mobile#57",
    repo: "acme-labs/mobile",
    number: 57,
    title: "Crash on cold start for Android 13",
    author: "noah",
    url: "https://github.com/acme-labs/mobile/pull/57",
    createdAt: "2026-08-18T09:30:00Z",
    updatedAt: "2026-08-18T13:12:00Z",
    ticket: {
      id: "ENG-436",
      title: "App crashes on launch, Android 13 only",
      description:
        "Wayne Enterprises sees an immediate crash on cold start on Android 13. Notification permission is requested before the activity is ready.\n\n**Claude review (unresolved):**\n> Move the permission request into onResume, and guard against a null activity - the crash trace shows it firing during onCreate.",
      url: "https://linear.app/acme-labs/issue/ENG-436",
      customerField: null,
      customer: null,
      filedBy: { name: "Noah Kim", email: "noah@acme-labs.example" },
    },
    customer: {
      name: "Bruce Wayne",
      email: "bruce@wayne.example",
      source: "supabase",
      verified: true,
      candidates: [],
      trail: ['name in ticket: "Bruce"', "supabase: 1 match"],
    },
    problem: "Cold-start crash on Android 13 - permission requested too early.",
    gate: {
      ciGreen: true,
      ciState: "passing",
      unresolvedBotReviews: 1,
      blockingBots: ["claude[bot]"],
    },
    mergeable: false,
    blockedReason: "1 unresolved bot review (claude[bot])",
  },
  {
    id: "acme-labs/web#118",
    repo: "acme-labs/web",
    number: 118,
    title: "Debounce search to cut API calls",
    author: "maya",
    url: "https://github.com/acme-labs/web/pull/118",
    createdAt: "2026-08-18T10:05:00Z",
    updatedAt: "2026-08-18T14:20:00Z",
    ticket: {
      id: "ENG-438",
      title: "Search box hammers the API on every keystroke",
      description:
        "Hooli noticed the search box fires a request per keystroke, spiking load. Add a 300ms debounce.",
      url: "https://linear.app/acme-labs/issue/ENG-438",
      customerField: null,
      customer: null,
      filedBy: { name: "Maya Chen", email: "maya@acme-labs.example" },
    },
    customer: {
      name: "Gavin",
      email: null,
      source: "posthog",
      verified: false,
      candidates: [
        { email: "gavin@hooli.example", source: "posthog", note: "Gavin Belson" },
        { email: "g.belson@hooli.example", source: "supabase", note: "G. Belson" },
      ],
      trail: ['name in ticket: "Gavin"', "2 candidates - needs a pick"],
    },
    problem: "Search fires a request per keystroke - needs debounce.",
    gate: {
      ciGreen: true,
      ciState: "passing",
      unresolvedBotReviews: 0,
      blockingBots: [],
    },
    mergeable: true,
    blockedReason: null,
  },
  {
    id: "acme-labs/api#506",
    repo: "acme-labs/api",
    number: 506,
    title: "Handle empty webhook payloads",
    author: "jordan",
    url: "https://github.com/acme-labs/api/pull/506",
    createdAt: "2026-08-18T11:40:00Z",
    updatedAt: "2026-08-18T15:55:00Z",
    ticket: {
      id: "ENG-441",
      title: "500s when a webhook body is empty",
      description:
        "Pied Piper's integration occasionally posts an empty body and we return a 500 instead of a 400. Validate before parsing.",
      url: "https://linear.app/acme-labs/issue/ENG-441",
      customerField: "Pied Piper",
      customer: {
        name: "Pied Piper",
        domains: ["piedpiper.example"],
        emails: ["richard@piedpiper.example"],
        tier: null,
      },
      filedBy: { name: "Jordan Lee", email: "jordan@acme-labs.example" },
    },
    customer: {
      name: "Pied Piper",
      email: "richard@piedpiper.example",
      source: "linear",
      verified: true,
      candidates: [],
      trail: ["linear customer record"],
    },
    problem: "Empty webhook body returns a 500 instead of a 400.",
    gate: {
      ciGreen: false,
      ciState: "failing",
      unresolvedBotReviews: 0,
      blockingBots: [],
    },
    mergeable: false,
    blockedReason: "CI not green",
  },
];
