import type { QueueItem } from "./types";

/** Fake queue so the app runs with zero credentials. */
export const mockQueue: QueueItem[] = [
  {
    id: "your-org/api#482",
    repo: "your-org/api",
    number: 482,
    title: "Login fails after password reset on mobile",
    author: "tuna",
    url: "https://github.com/your-org/api/pull/482",
    createdAt: "2026-08-16T09:12:00Z",
    updatedAt: "2026-08-17T08:40:00Z",
    ticket: {
      id: "ENG-311",
      title: "Login fails after password reset on mobile",
      description:
        "Customer Jane Doe (Acme) reports that after resetting their password from the iOS app, they land on a blank screen and can't sign in. Reproduced on iOS 18.2, app 4.3.1. Desktop web works fine. They need this fixed before Monday's board demo.",
      url: "https://linear.app/your-org/issue/ENG-311",
      customerField: "Acme",
      customer: {
        name: "Acme",
        domains: ["acme.com"],
        emails: ["jane@acme.com"],
        tier: null,
      },
      filedBy: { name: "Tuna", email: "tuna@slashy.com" },
    },
    customer: {
      name: "Acme",
      email: "jane@acme.com",
      source: "linear",
      verified: true,
      candidates: [],
      trail: ["email found in ticket text"],
    },
    problem: "After reset on iOS they hit a blank screen and can't sign in.",
    gate: { ciGreen: true, ciState: "passing", unresolvedBotReviews: 0, blockingBots: [] },
    mergeable: true,
    blockedReason: null,
  },
  {
    id: "your-org/web#91",
    repo: "your-org/web",
    number: 91,
    title: "Billing webhook retry loop",
    author: "linh",
    url: "https://github.com/your-org/web/pull/91",
    createdAt: "2026-08-16T14:03:00Z",
    updatedAt: "2026-08-16T18:20:00Z",
    ticket: {
      id: "ENG-402",
      title: "Duplicate invoices from webhook retries",
      description:
        "Beta Corp saw duplicate invoices when our billing webhook retried on timeout. Need idempotency keys on the handler.",
      url: "https://linear.app/your-org/issue/ENG-402",
      customerField: null,
      customer: null,
      filedBy: { name: "Linh", email: "linh@slashy.com" },
    },
    customer: {
      name: "Sam Lee",
      email: "sam@beta.io",
      source: "supabase",
      verified: true,
      candidates: [],
      trail: ['name in ticket: "Sam Lee"', "supabase: 1 match"],
    },
    problem: "Duplicate invoices from webhook retries - needs idempotency.",
    gate: { ciGreen: true, ciState: "passing", unresolvedBotReviews: 2, blockingBots: ["coderabbitai[bot]"] },
    mergeable: false,
    blockedReason: "2 unresolved bot reviews (coderabbitai[bot])",
  },
  {
    id: "your-org/api#488",
    repo: "your-org/api",
    number: 488,
    title: "Add rate limit to export endpoint",
    author: "tuna",
    url: "https://github.com/your-org/api/pull/488",
    createdAt: "2026-08-17T02:40:00Z",
    updatedAt: "2026-08-17T05:10:00Z",
    ticket: {
      id: "ENG-410",
      title: "Export endpoint abused by a script",
      description:
        "A user hammered the export endpoint. Add a per-user rate limit. Reporter only left a first name in the thread: 'Priya'.",
      url: "https://linear.app/your-org/issue/ENG-410",
      customerField: null,
      customer: null,
      filedBy: { name: "Tuna", email: "tuna@slashy.com" },
    },
    customer: {
      name: "Priya",
      email: null,
      source: "posthog",
      verified: false,
      candidates: [
        { email: "priya@globex.com", source: "posthog", note: "Priya Nair" },
        { email: "priya.n@globex.io", source: "supabase", note: "Priya N." },
      ],
      trail: ['name in ticket: "Priya"', "2 candidates - needs a pick"],
    },
    problem: "Export endpoint abused - add per-user rate limit.",
    gate: { ciGreen: false, ciState: "failing", unresolvedBotReviews: 0, blockingBots: [] },
    mergeable: false,
    blockedReason: "CI not green",
  },
];
